// Auto-generated manifest of local cigar images for production bundling
// Maps filename -> required asset module

export const cigarImageManifest: Record<string, any> = {
  '15_romeo_y_julieta_wide_churchhill.jpg': require('../../assets/Cigar_Images/15_romeo_y_julieta_wide_churchhill.jpg'),
  'West-Tampa-Red-Robusto.jpg': require('../../assets/Cigar_Images/West-Tampa-Red-Robusto.jpg'),
  'Trinidad-Espiritu-Series-No.-1-Belicoso.jpg': require('../../assets/Cigar_Images/Trinidad-Espiritu-Series-No.-1-Belicoso.jpg'),
  'San-Cristobal-Clasico.jpg': require('../../assets/Cigar_Images/San-Cristobal-Clasico.jpg'),
  'rocky-patel-sixty-six.jpg': require('../../assets/Cigar_Images/rocky-patel-sixty-six.jpg'),
  'Rocky-Patel-A.L.R-Second-Edition-Toro.jpg': require('../../assets/Cigar_Images/Rocky-Patel-A.L.R-Second-Edition-Toro.jpg'),
  'Rafael-Gonzalez-Corona-de-Lonsdale.jpg': require('../../assets/Cigar_Images/Rafael-Gonzalez-Corona-de-Lonsdale.jpg'),
  'Padron-1964-Anniversary-Series-Principe.jpg': require('../../assets/Cigar_Images/Padron-1964-Anniversary-Series-Principe.jpg'),
  'Ozgener-Family-Cigars-Bosphorus-B52.jpg': require('../../assets/Cigar_Images/Ozgener-Family-Cigars-Bosphorus-B52.jpg'),
  'Olmec-Claro-Corona-Gorda.jpg': require('../../assets/Cigar_Images/Olmec-Claro-Corona-Gorda.jpg'),
  'New-World-Dorado-Robusto.jpg': require('../../assets/Cigar_Images/New-World-Dorado-Robusto.jpg'),
  'Long-Live-The-Queen-Ace-of-Hearts.jpg': require('../../assets/Cigar_Images/Long-Live-The-Queen-Ace-of-Hearts.jpg'),
  'Joya-de-Nicaragua-Antano-1970-Churchill.jpg': require('../../assets/Cigar_Images/Joya-de-Nicaragua-Antano-1970-Churchill.jpg'),
  'Illusione-Rothchildes.jpg': require('../../assets/Cigar_Images/Illusione-Rothchildes.jpg'),
  'Illusione-Allegria-Robusto.jpg': require('../../assets/Cigar_Images/Illusione-Allegria-Robusto.jpg'),
  'Hoyo-de-Monterrey-Elegantes.jpg': require('../../assets/Cigar_Images/Hoyo-de-Monterrey-Elegantes.jpg'),
  'H-Upmann-Magnum-56.jpg': require('../../assets/Cigar_Images/H-Upmann-Magnum-56.jpg'),
  'H-Upmann-0No.2.jpg': require('../../assets/Cigar_Images/H-Upmann-0No.2.jpg'),
  'Fuente-Fuente-OpusX-Reserva-dChateau.jpg': require('../../assets/Cigar_Images/Fuente-Fuente-OpusX-Reserva-dChateau.jpg'),
  'foreign-Affair-By-Luciano-Cigars-Corona.jpg': require('../../assets/Cigar_Images/foreign-Affair-By-Luciano-Cigars-Corona.jpg'),
  'Espinosa-Knuckle-Sandwich-Habano-Corona-Gorda-R.jpg': require('../../assets/Cigar_Images/Espinosa-Knuckle-Sandwich-Habano-Corona-Gorda-R.jpg'),
  'E.P.-Carrillo-Pledge-Apogee.jpg': require('../../assets/Cigar_Images/E.P.-Carrillo-Pledge-Apogee.jpg'),
  'E.P.-Carrillo-Encore-Celestial.jpg': require('../../assets/Cigar_Images/E.P.-Carrillo-Encore-Celestial.jpg'),
  'DrewEstate-Liga-Privad-No.9-Belicoso.jpg': require('../../assets/Cigar_Images/DrewEstate-Liga-Privad-No.9-Belicoso.jpg'),
  'Davidoff-Nicaragua-Diadema.jpg': require('../../assets/Cigar_Images/Davidoff-Nicaragua-Diadema.jpg'),
  'Davidoff-Millennium-Blend-Robusto.jpg': require('../../assets/Cigar_Images/Davidoff-Millennium-Blend-Robusto.jpg'),
  'C.A.O- BRAZILIA-GOL.jpg': require('../../assets/Cigar_Images/C.A.O- BRAZILIA-GOL.jpg'),
  'ASHTON-Vsg-ENCHANTMENT.jpg': require('../../assets/Cigar_Images/ASHTON-Vsg-ENCHANTMENT.jpg'),
  'Ashton-Virgin-Sun-Grown-Illusion.jpg': require('../../assets/Cigar_Images/Ashton-Virgin-Sun-Grown-Illusion.jpg'),
  'arturo-fuente-rare-pink-vintage.jpg': require('../../assets/Cigar_Images/arturo-fuente-rare-pink-vintage.jpg'),
  'Arturo-fuente-opusx.jpg': require('../../assets/Cigar_Images/Arturo-fuente-opusx.jpg'),
  'Arturo-Fuente-Hemingway.jpg': require('../../assets/Cigar_Images/Arturo-Fuente-Hemingway.jpg'),
  'Arturo-Fuente-Hemingway-Between-the-Lines.jpg': require('../../assets/Cigar_Images/Arturo-Fuente-Hemingway-Between-the-Lines.jpg'),
  'arturo-fuente-don-carlos-eye-of-the-shark.jpg': require('../../assets/Cigar_Images/arturo-fuente-don-carlos-eye-of-the-shark.jpg'),
  'alec-bradley-prensado-lost-art-gordo.jpg': require('../../assets/Cigar_Images/alec-bradley-prensado-lost-art-gordo.jpg'),
  'alec-bradley_black_market_churchill.jpg': require('../../assets/Cigar_Images/alec-bradley_black_market_churchill.jpg'),
  'Warped_Corto_X52.jpeg': require('../../assets/Cigar_Images/Warped_Corto_X52.jpeg'),
  'Tatuaje_Reserva_A_Uno.jpeg': require('../../assets/Cigar_Images/Tatuaje_Reserva_A_Uno.jpeg'),
  'Rocky_Patel_Conviction_Toro.jpeg': require('../../assets/Cigar_Images/Rocky_Patel_Conviction_Toro.jpeg'),
  'Perdomo_30th_Anniversary_Sun Grown_Epicure.jpeg': require('../../assets/Cigar_Images/Perdomo_30th_Anniversary_Sun Grown_Epicure.jpeg'),
  'Partagas_Linea_Maestra_Maestro.jpeg': require('../../assets/Cigar_Images/Partagas_Linea_Maestra_Maestro.jpeg'),
  'my_father_judge_grand_robusto_listing.jpeg': require('../../assets/Cigar_Images/my_father_judge_grand_robusto_listing.jpeg'),
  'montecristo_1935_anniversary_nicaragua_espeso_listing.jpeg': require('../../assets/Cigar_Images/montecristo_1935_anniversary_nicaragua_espeso_listing.jpeg'),
  'La_Aroma_de_Cuba_Pasion_Box-Pressed Torpedo.jpeg': require('../../assets/Cigar_Images/La_Aroma_de_Cuba_Pasion_Box-Pressed Torpedo.jpeg'),
  'Herrera_Esteli_Norteno_Lonsdale.jpeg': require('../../assets/Cigar_Images/Herrera_Esteli_Norteno_Lonsdale.jpeg'),
  'Cohiba_Maduro_5_Magicos.jpeg': require('../../assets/Cigar_Images/Cohiba_Maduro_5_Magicos.jpeg'),
  'Casa_Magna_Colorado_XV_Anniversary.jpeg': require('../../assets/Cigar_Images/Casa_Magna_Colorado_XV_Anniversary.jpeg'),
  '2023_10_el_pulpo_belicoso_grande.jpeg': require('../../assets/Cigar_Images/2023_10_el_pulpo_belicoso_grande.jpeg'),
  '2023_09_la_aroma_de_cuba_mi_amor_belicoso.jpeg': require('../../assets/Cigar_Images/2023_09_la_aroma_de_cuba_mi_amor_belicoso.jpeg'),
  '2023_08_alec_bradley_prensado_torpedo.jpeg': require('../../assets/Cigar_Images/2023_08_alec_bradley_prensado_torpedo.jpeg'),
  '2023_07_blackened_cigars_m81_drew_estate_corona.jpeg': require('../../assets/Cigar_Images/2023_07_blackened_cigars_m81_drew_estate_corona.jpeg'),
  '2023_06_partagas_serie_p_no_2.jpeg': require('../../assets/Cigar_Images/2023_06_partagas_serie_p_no_2.jpeg'),
  '2023_05_ep_carrillo_allegiance_confidant.jpeg': require('../../assets/Cigar_Images/2023_05_ep_carrillo_allegiance_confidant.jpeg'),
  '2023_02_padron_serie_1926_no_48_maduro.jpeg': require('../../assets/Cigar_Images/2023_02_padron_serie_1926_no_48_maduro.jpeg'),
  '2023_01_fuente_fuente_opusx_reserva_dchateau.jpeg': require('../../assets/Cigar_Images/2023_01_fuente_fuente_opusx_reserva_dchateau.jpeg'),
  '601_La_Bomba_Warhead_X.jpg': require('../../assets/Cigar_Images/601_La_Bomba_Warhead_X.jpg'),
  '25_tatuaje_reserva_a_uno.jpeg': require('../../assets/Cigar_Images/25_tatuaje_reserva_a_uno.jpeg'),
  '23_warped_corto_x52.jpeg': require('../../assets/Cigar_Images/23_warped_corto_x52.jpeg'),
  '19_herrera_esteli_norteno_lonsdale.jpeg': require('../../assets/Cigar_Images/19_herrera_esteli_norteno_lonsdale.jpeg'),
  '16_perdomo_30th_anniversary_sun_grown_epicure.jpeg': require('../../assets/Cigar_Images/16_perdomo_30th_anniversary_sun_grown_epicure.jpeg'),
  '14_casa_magna_colorado_xv_anniversary.jpeg': require('../../assets/Cigar_Images/14_casa_magna_colorado_xv_anniversary.jpeg'),
  '11_la_aroma_de_cuba_pasion_box_pressed_torpedo.jpeg': require('../../assets/Cigar_Images/11_la_aroma_de_cuba_pasion_box_pressed_torpedo.jpeg'),
  '10_brick_house_churchill.jpeg': require('../../assets/Cigar_Images/10_brick_house_churchill.jpeg'),
  '08_cohiba_maduro_5_magicos.jpeg': require('../../assets/Cigar_Images/08_cohiba_maduro_5_magicos.jpeg'),
  '06_oliva_serie_v_melanio_maduro_torpedo.jpg': require('../../assets/Cigar_Images/06_oliva_serie_v_melanio_maduro_torpedo.jpg'),
  '05_partagas_linea_maestra_maestro.jpeg': require('../../assets/Cigar_Images/05_partagas_linea_maestra_maestro.jpeg'),
  '02_montecristo_1935_anniversary_nicaragua_espeso.jpeg': require('../../assets/Cigar_Images/02_montecristo_1935_anniversary_nicaragua_espeso.jpeg'),
  '01_my_father_judge_grand_robusto.jpeg': require('../../assets/Cigar_Images/01_my_father_judge_grand_robusto.jpeg'),
};



